Create remove books
initseis/bookstore pull request #2
Opened 2021-08-24 16:10 UTC by sevinchek

In this branch I:

- Used Redux duck-pattern
- Setup the books reducer
- Setup the configureStore
- Used redux-logger
- Update components to add and remove books

2021-08-24 16:59 UTC, bellom requested changes
## Hi @sevinchek  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Let's make your repo looks professional by updating your `README` file**.
Checkout out the below link for help, feel free to follow this [Microverse template](https://github.com/microverseinc/readme-template) from pathwright

**Kindly check my comments under this review;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best**

2021-08-24 16:59 UTC, bellom commented on src/components/Form.js
>    const generateId = () => {
### [Optional]

Great job creating this function but you could have simply use [npm uuid](https://www.npmjs.com/package/uuidv4)

2021-08-24 17:30 UTC, Emmyn5600 approved these changes
Hi, 

Good job so far! 👏🏼 @sevinchek 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSE
 
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-25 14:53 UTC, sevinchek commented
Thanks.

2021-08-25 14:53 UTC, merged